[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
lib_deps =
    madhephaestus/ESP32Servo@^3.0.0
    nRF24/RF24@^1.4.10
    ESP3232Servo
monitor_speed = 115200

[env:transmitter]
build_flags = -D TRANSMITTER

[env:receiver]
build_flags = -D RECEIVER
